// constants/errorCodes.js

const ErrorCodes = {
    // Authentication Errors
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    PASSWORDLESS_ACCOUNT: 'PASSWORDLESS_ACCOUNT',
    ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

    // Token / OTP Errors
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOO_MANY_RESEND_ATTEMPTS: 'TOO_MANY_RESEND_ATTEMPTS',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    // Authorization
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    // User Profile
    USERNAME_TAKEN: 'USERNAME_TAKEN',
    PASSWORD_ALREADY_SET: 'PASSWORD_ALREADY_SET',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // Rate Limiting
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

    // Server Errors
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

    // Passwordless Specific
    LOGIN_CODE_EXPIRED: 'LOGIN_CODE_EXPIRED',
};

module.exports = ErrorCodes;