module.exports = {
    // Auth
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_REGISTER: 'AUTH_REGISTER',
    AUTH_FAILED_LOGIN: 'AUTH_FAILED_LOGIN',

    // User
    USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE',

    // Content
    POST_CREATE: 'POST_CREATE',
    POST_DELETE: 'POST_DELETE',


    // Security
    TOKEN_INVALID: "TOKEN_INVALID",
    UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS'
}